[package]
name = "xivar"
version = "0.4.0"
authors = ["Alexander Lindermayr <alexander.lindermayr97@gmail.com>"]
edition = "2021"
license = "MIT"
description = "Manage your local scientific library"
repository = "https://github.com/Mountlex/xivar"
readme = "README.md"
keywords = ["arXiv", "cli", "dblp", "download", "database"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.4.2"
dirs-next = "2.0.0"
serde = { version = "1.0.118", features = ["derive"]}
anyhow = "1.0.35"
bincode = "1.3.1"
tempfile = "3.1.0"
clap = { version = "3.1.6", features = ["derive"] }
surf = "2.1.0"
dialoguer = "0.10.0"
async-std = { version = "1.10.0", features = ["unstable"] }
futures = "0.3.8"
open = "2.1.1"
itertools = "0.10.3"
console = "0.15.0"
config = "0.12.0"
indicatif = "0.16.2"
roxmltree = "0.14.1"
lopdf = "0.27.0"
async-trait = "0.1.52"
skim = "0.9.3"
proc-macro2 = "1.0.36"
