[package]
name = "xivar"
version = "0.1.0"
authors = ["Alexander Lindermayr <alexander.lindermayr97@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.4.2"
dirs = "3.0.1"
serde = { version = "1.0.117", features = ["derive"]}
anyhow = "1.0.34"
bincode = "1.3.1"
tempfile = "3.1.0"
clap = "3.0.0-beta.2"
arxiv-rs = "0.1.2"
surf = "2.1.0"
dialoguer = "0.7.1"
async-trait = "0.1.42"
async-std = { version = "1.7.0", features = ["attributes"] }